apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: dbt-gar-example
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: asia-docker.pkg.dev/briancao/data/dbt
      context: .
      docker:
        dockerfile: Dockerfile
  # googleCloudBuild:
  #   projectId: 
  local:
    push: false
# deploy:
#   kubectl:
#     manifests:
#       - k8s/deployment.yaml  # Optional if deploying to Kubernetes
